### ISSUE TITLE
可以提供主題切換的功能嗎

### ISSUE THREAD

**Issue by LRboyz** [surmon-china/veact-admin#1]
希望能夠支持亮模式的主題

**Comment by surmon-china** [comment]
暂时没有，今后可能会增加。

**Comment by Zeven-Up** [comment]
Hi, I try to run but, I can't login to dashboard. It's always show network error message. 
![2023-10-31_15-34-08](https://github.com/surmon-china/veact-admin/assets/20995837/27bc09bf-a197-4658-98d1-6db1125dc24e)
Pls, advice.

**Comment by surmon-china** [comment]
Now! [DEMO site](https://github.surmon.me/veact-admin/#/dashboard)

<img width="1422" alt="image" src="https://github.com/surmon-china/veact-admin/assets/14019524/2dbe6ced-7b75-4246-bbf5-bc7f11bc4030">
